POST http://localhost:3000/register
Content-Type:application/json

{
  "username": "miller",
  "name": "Adam miller",
  "password": "richard_567",
  "gender": "male",
  "location": "Detroit"
}

###
POST http://localhost:3000/login
Content-Type:application/json

{
  "username": "miller",
  "password": "richard_567"
}

###
PUT http://localhost:3000/change-password
Content-Type:application/json

{
  "username": "miller",
  "oldPassword": "richard_567",
  "newPassword": "richard@123"
}